version: '3'

services:
  backend:
    build: ./backend
    ports:
     - 3001:3001
    environment:
     - DB_TYPE=postgres
     - DB_HOST=localhost
     - DB_SCHEMA=public
     - DB_NAME=postgres
     - DB_USER=postgres
     - DB_PASS=postgres
  
